name       : tini
version    : 0.19.0
release    : 1
source     :
    - https://github.com/krallin/tini/archive/refs/tags/v0.19.0.tar.gz : 0fd35a7030052acd9f58948d1d900fe1e432ee37103c5561554408bdac6bbf0d
license    : MIT
component  : virt
summary    : A tiny but valid init for containers
description: |
    A tiny but valid init for containers
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
